"""add_chat_tables

Revision ID: 46049293d5a8
Revises: 445652e385c7
Create Date: 2025-11-14 07:14:04.648569+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from ohra.alembic.migrations.utils import get_existing_tables


# revision identifiers, used by Alembic.
revision: str = "46049293d5a8"
down_revision: Union[str, None] = "445652e385c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    existing_tables = set(get_existing_tables())  # noqa: F841
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ohra_feedback",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ohra_feedback_message_id"), "ohra_feedback", ["message_id"], unique=False)
    op.create_index(op.f("ix_ohra_feedback_user_id"), "ohra_feedback", ["user_id"], unique=False)
    op.create_table(
        "ohra_message",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ohra_message_conversation_id"), "ohra_message", ["conversation_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    existing_tables = set(get_existing_tables())  # noqa: F841
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ohra_message_conversation_id"), table_name="ohra_message")
    op.drop_table("ohra_message")
    op.drop_index(op.f("ix_ohra_feedback_user_id"), table_name="ohra_feedback")
    op.drop_index(op.f("ix_ohra_feedback_message_id"), table_name="ohra_feedback")
    op.drop_table("ohra_feedback")
    # ### end Alembic commands ###
